name: Build Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: allot-1564297177224
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for Google Cloud Registry
        run: gcloud auth configure-docker

      - name: Build & Push Docker image
        run: docker buildx build -t us.gcr.io/allot-1564297177224/docker-airflow -f ./src/Dockerfile --push --platform=linux/arm64,linux/amd64 ./src